version: '3'
services:
  web_app:
      build:
          context: .
          dockerfile: src/web_app/Dockerfile
      image: streamlit_web_app
      container_name: streamlit_web_app
      ports:
          - "8501:8501"
      command: streamlit run src/web_app/web_app.py
  mlflow:
      restart: always
      build:
          context: .
          dockerfile: mlflow/Dockerfile
      image: mlflow_server
      container_name: mlflow_server
      ports:
          - "5000:5000"
      environment:
          - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
          - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
          - AWS_DEFAULT_REGION=${AWS_REGION}
      command: mlflow server -h 0.0.0.0 --default-artifact-root s3://${AWS_BUCKET_NAME}
  postgres:
      image: postgres:10.5
      container_name: postgres_db
      restart: always
      environment:
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      ports:
          - '5432:5432'
      volumes: 
          - ./postgres_data:/var/lib/postgresql/data 
